spring:
  threads:
    virtual:
      enabled: true

xredis:
  lettuce: # Lettuce 客户端配置
    id: lettuce # RedisOperatorFactory 唯一标识
    standalone: # 单机模式 或 副本集模式
      nodes: 127.0.0.1:6380, 127.0.0.1:6379 # Redis 节点列表