spring:
  threads:
    virtual:
      enabled: true

xredis:
  lettuce: # Lettuce 客户端配置
    id: lettuce # RedisOperatorFactory 唯一标识
    standalone: # 单机模式 或 副本集模式
      node: 127.0.0.1:6380 # Redis 节点，支持 UnixSocket 方式
