xredis:
  lettuce: # Lettuce 客户端配置
    id: lettuce # RedisOperatorFactory 唯一标识
    standalone: # 单机模式 或 副本集模式
      # 这里为了演示 standalone，sentinel，cluster 分别如何配置，所以三种配置都存在，实际只需保留真正使用的其中一种
      # 当三种配置都存在时，那么优先使用 sentinel 配置，其次 cluster，最后 standalone
      node: 127.0.0.1:6379 # Redis 节点（支持 UnixSocket 方式）
      nodes: 127.0.0.1:6378 # Redis 节点列表（如 nodes 无配置，主动发现并连接新节点；如 nodes 有配置，仅连接已配置的节点）
      read-from: # 读节点选择策略（默认值：UPSTREAM，仅从主节点读取数据）
      username: # Redis 用户名
      password: # Redis 密码
      database: 0 # Redis 数据库索引（默认值：0）
      client-name: # Redis 客户端名称
      ssl: false # 是否启用 SSL（默认值：false）
      start-tls: false # 是否启用 TLS（默认值：false）
      ssl-verify-mode: FULL # SSL 验证模式，只有 ssl 配置为 true 时才有意义（默认值：FULL）
      timeout: 60000 # 命令响应的最大等待时长（默认值：60000 单位：毫秒）
      shutdown-timeout: 2000 # 优雅停机最大等待时长（默认值：1000 单位：毫秒）
      shutdown-quiet-period: 100 # 优雅停机静默时长（默认值：100 单位：毫秒）
      client-options: # 客户端选项，一般保持默认即可
        auto-reconnect: true # 是否自动重连（默认值：true）
        disconnected-behavior: DEFAULT # 连接断开后是否接受命令（默认值：DEFAULT）
        publish-on-scheduler: false # 是否使用专用的 scheduler 处理 publish 事件（默认值：false）
        ping-before-activate-connection: true # 连接激活前是否发送 PING 消息（默认值：true）
        protocol-version: RESP2 # Redis 协议版本（默认值：RESP3，Redis 6.0 以下请配置为 RESP2）
        suspend-reconnect-on-protocol-failure: # 是否在协议失败时暂停重连（默认值：false）
        request-queue-size: # 请求队列大小 （默认值：Integer.MAX_VALUE）
        socket-options: # socket 配置选项
          connect-timeout: 10000 # Socket 连接超时（默认值：10000， 单位：毫秒）
          tcp-no-delay: true  # 是否启用 TCP_NODELAY（默认值：true）
          keep-alive: # KeepAlive 配置选项，仅适用于 epoll、 io_uring、Java 11 及之后版本的 NIO
            enabled: false # 是否启用 KeepAlive（默认值：false）
            count: 9 # KeepAlive 重试次数（默认值：9）
            idle: 7200000 # KeepAlive 空闲时间（默认值：7200000， 单位：毫秒）
            interval: 75000 # KeepAlive 发送间隔（默认值：75000， 单位：毫秒）
          tcp-user-timeout: # TCP_USER_TIMEOUT 配置选项，仅适用于 epoll 和 io_uring
            enabled: false # 是否启用 TCP_USER_TIMEOUT（默认值：false）
            tcp-user-timeout: 7875000 # TCP 超时配置（默认值：7875000 单位：毫秒）
        ssl-options: # SSL 配置选项，只有 ssl 配置为 true 时才有意义
          ssl-provider: JDK # （默认值：JDK）
          key-store-type: # 密钥库格式（默认值：jks）
          keystore: # 密钥库路径
          keystore-password: # 密钥库密码
          truststore: # 信任库路径
          truststore-password: # 信任库密码
          protocols: # 支持的安全协议
          cipher-suites: # 支持的加密套件
          handshake-timeout: # 握手超时（默认值：10000 单位：毫秒）
        timeout-options: # 命令超时配置选项
          fixedTimeout: # 固定超时时间（默认值：-1，单位：毫秒，无超时配置）
    sentinel: # 哨兵模式配置
      # 这里为了演示 standalone，sentinel，cluster 分别如何配置，所以三种配置都存在，实际只需保留真正使用的其中一种
      # 当三种配置都存在时，那么优先使用 sentinel 配置，其次 cluster，最后 standalone
      master-id: mymaster # 哨兵主节点名称
      nodes: 127.0.0.1:26377, 127.0.0.1:26378, 127.0.0.1:26379 # 哨兵节点列表
      read-from: # 读节点选择策略（默认值：UPSTREAM，仅从主节点读取数据）
      sentinel-username:  # 哨兵用户名
      sentinel-password:  # 哨兵密码
      username:  # Redis 用户名
      password:  # Redis 密码
      database: 0 # Redis 数据库索引（默认值：0）
      client-name: # Redis 客户端名称
      ssl: false # 是否启用 SSL（默认值：false）
      start-tls: false # 是否启用 TLS（默认值：false）
      ssl-verify-mode: FULL # SSL 验证模式，只有 ssl 配置为 true 时才有意义（默认值：FULL）
      timeout:  # 命令响应的最大等待时长（默认值：60000 单位：毫秒）
      shutdown-timeout: 2000 # 优雅停机最大等待时长（默认值：1000 单位：毫秒）
      shutdown-quiet-period: 100 # 优雅停机静默时长（默认值：100 单位：毫秒）
      client-options: # 客户端选项，一般保持默认即可
        auto-reconnect: true # 是否自动重连（默认值：true）
        disconnected-behavior: DEFAULT # 连接断开后是否接受命令（默认值：DEFAULT）
        publish-on-scheduler: false # 是否使用专用的 scheduler 处理 publish 事件（默认值：false）
        ping-before-activate-connection: true # 连接激活前是否发送 PING 消息（默认值：true）
        protocol-version: RESP2 # Redis 协议版本（默认值：RESP3，Redis 6.0 以下请配置为 RESP2）
        suspend-reconnect-on-protocol-failure: # 是否在协议失败时暂停重连（默认值：false）
        request-queue-size: # 请求队列大小 （默认值：Integer.MAX_VALUE）
        socket-options: # socket 配置选项
          connect-timeout: 10000 # Socket 连接超时（默认值：10000， 单位：毫秒）
          tcp-no-delay: true  # 是否启用 TCP_NODELAY（默认值：true）
          keep-alive: # KeepAlive 配置选项，仅适用于 epoll、 io_uring、Java 11 及之后版本的 NIO
            enabled: false # 是否启用 KeepAlive（默认值：false）
            count: 9 # KeepAlive 重试次数（默认值：9）
            idle: 7200000 # KeepAlive 空闲时间（默认值：7200000， 单位：毫秒）
            interval: 75000 # KeepAlive 发送间隔（默认值：75000， 单位：毫秒）
          tcp-user-timeout: # TCP_USER_TIMEOUT 配置选项，仅适用于 epoll 和 io_uring
            enabled: false # 是否启用 TCP_USER_TIMEOUT（默认值：false）
            tcp-user-timeout: 7875000 # TCP 超时配置（默认值：7875000 单位：毫秒）
        ssl-options: # SSL 配置选项，只有 ssl 配置为 true 时才有意义
          ssl-provider: JDK # （默认值：JDK）
          key-store-type: # 密钥库格式（默认值：jks）
          keystore: # 密钥库路径
          keystore-password: # 密钥库密码
          truststore: # 信任库路径
          truststore-password: # 信任库密码
          protocols: # 支持的安全协议
          cipher-suites: # 支持的加密套件
          handshake-timeout: # 握手超时（默认值：10000 单位：毫秒）
        timeout-options: # 命令超时配置选项
          fixedTimeout: # 固定超时时间（默认值：-1，单位：毫秒，无超时配置）
    cluster: # 集群模式配置
      # 这里为了演示 standalone，sentinel，cluster 分别如何配置，所以三种配置都存在，实际只需保留真正使用的其中一种
      # 当三种配置都存在时，那么优先使用 sentinel 配置，其次 cluster，最后 standalone
      nodes: 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004, 127.0.0.1:7005, 127.0.0.1:7006 # 集群节点列表
      read-from: # 读节点选择策略（默认值：UPSTREAM，仅从主节点读取数据）
      username: redis-admin # Redis 用户名
      password: 123456 # Redis 密码
      database: 0 # Redis 数据库索引（默认值：0）
      client-name: # Redis 客户端名称
      ssl: false # 是否启用 SSL（默认值：false）
      start-tls: false # 是否启用 TLS（默认值：false）
      ssl-verify-mode: FULL # SSL 验证模式，只有 ssl 配置为 true 时才有意义（默认值：FULL）
      timeout:  # 命令响应的最大等待时长（默认值：60000 单位：毫秒）
      shutdown-timeout: 2000 # 客户端关闭超时（默认值：1000 单位：毫秒）
      shutdown-quiet-period: 100 # 优雅停机静默时长（默认值：100 单位：毫秒）
      client-options: # 集群客户端选项，一般保持默认即可
        auto-reconnect: true # 是否自动重连（默认值：true）
        disconnected-behavior: DEFAULT # 连接断开后是否接受命令（默认值：DEFAULT）
        ping-before-activate-connection: true # 连接激活前是否发送 PING 消息（默认值：true）
        protocol-version: RESP2 # Redis 协议版本（默认值：RESP3，Redis 6.0 以下请配置为 RESP2）
        publish-on-scheduler: false # 是否使用专用的 scheduler 处理 publish 事件（默认值：false）
        request-queue-size: # 请求队列大小 （默认值：Integer.MAX_VALUE）
        suspend-reconnect-on-protocol-failure: # 是否在协议失败时暂停重连（默认值：false）
        max-redirects: # 集群重定向最大重试次数（默认值：5）
        validate-cluster-node-membership: # 是否验证集群节点成员关系（默认值：true）
        node-filter:    # 建立连接的节点[白名单] （如未配置，连接所有节点；如有配置，只连接配置节点）
        topology-refresh-options: # 节点拓扑刷新配置选项
          adaptive-refresh-triggers: # 动态刷新触发器，列表类型（默认为空集）
          adaptive-refresh-timeout: # 动态刷新超时（默认值：30000 单位：毫秒）
          close-stale-connections: # 是否关闭旧连接（默认值：true）
          dynamic-refresh-sources: # 是否动态刷新节点源（默认值：true）
          periodic-refresh-enabled: # 是否启用周期刷新（默认值：true）
          refresh-period: # 刷新周期 （默认值：30000 单位：毫秒）
          refresh-triggers-reconnect-attempts: # 刷新触发器重连尝试次数（默认值：3）
        socket-options: # socket 配置选项
          connect-timeout: 10000 # Socket 连接超时（默认值：10000， 单位：毫秒）
          tcp-no-delay: true  # 是否启用 TCP_NODELAY（默认值：true）
          keep-alive: # KeepAlive 配置选项，仅适用于 epoll、 io_uring、Java 11 及之后版本的 NIO
            enabled: false # 是否启用 KeepAlive（默认值：false）
            count: 9 # KeepAlive 重试次数（默认值：9）
            idle: 7200000 # KeepAlive 空闲时间（默认值：7200000， 单位：毫秒）
            interval: 75000 # KeepAlive 发送间隔（默认值：75000， 单位：毫秒）
          tcp-user-timeout: # TCP_USER_TIMEOUT 配置选项，仅适用于 epoll 和 io_uring
            enabled: false # 是否启用 TCP_USER_TIMEOUT（默认值：false）
            tcp-user-timeout: 7875000 # TCP 超时配置（默认值：7875000 单位：毫秒）
        ssl-options: # SSL 配置选项，只有 ssl 配置为 true 时才有意义
          ssl-provider: JDK # （默认值：JDK）
          key-store-type: # 密钥库格式（默认值：jks）
          keystore: # 密钥库路径
          keystore-password: # 密钥库密码
          truststore: # 信任库路径
          truststore-password: # 信任库密码
          protocols: # 支持的安全协议
          cipher-suites: # 支持的加密套件
          handshake-timeout: # 握手超时（默认值：10000 单位：毫秒）
        timeout-options: # 命令超时配置选项
          fixedTimeout: # 固定超时时间（默认值：-1，单位：毫秒，无超时配置）
